version: 2
updates:
  # npm（フロントエンド）の依存関係を維持
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "nakazawatarou"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      frontend-deps:
        patterns:
          - "*"

  # npm（バックエンド）の依存関係を維持
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "nakazawatarou"
    labels:
      - "dependencies"
      - "backend"
    groups:
      backend-deps:
        patterns:
          - "*"

  # npm（共通パッケージ）の依存関係を維持
  - package-ecosystem: "npm"
    directory: "/packages/shared-types"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "nakazawatarou"
    labels:
      - "dependencies"
      - "shared"
    groups:
      shared-deps:
        patterns:
          - "*"

  # ルートの依存関係を維持
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actionsの依存関係を維持
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
